### ISSUE TITLE
View mode for Area not showing quest hours

### ISSUE THREAD

**Issue by svenberg** [UnownHash/Dragonite-Public#19]
When I view any of my quest enabled areas it doesn't show any quest hours.

Areas overview
![image](https://github.com/UnownHash/Dragonite-Public/assets/46693744/096dabf1-a83b-43bc-8c53-cf3005a23727)

View mode
![image](https://github.com/UnownHash/Dragonite-Public/assets/46693744/12b4701e-99c0-42c7-8d45-7e3d3ad1435b)

Edit mode
![image](https://github.com/UnownHash/Dragonite-Public/assets/46693744/eacbe60a-4e63-48ae-ac7e-b8242768da4e)

**Comment by Fabio1988** [comment]
resolved, if you still see that issue pls reopen
