### ISSUE TITLE
Dragonite version mismatch

### ISSUE THREAD

**Issue by clburlison** [UnownHash/Dragonite-Public#3]
Super cosmetic. Likely a pain in the butt at the moment but versions don't match between Github Release and cli output. Can see this being a larger problem in the future as "User says I'm running version X but they're actually on XY"

```
INFO 2023-11-12 10:07:40 [] Starting Dragonite Public 1.0.0
```

While the download was from [v1.0.1](https://github.com/UnownHash/Dragonite-Public/releases/tag/dragonite-v1.0.1)

**Comment by Fabio1988** [comment]
fixed in next release
