### ISSUE TITLE
Dragonite updates `last_refreshed` too early

### ISSUE THREAD

**Issue by XerockXMG** [UnownHash/Dragonite-Public#33]
It seems that Dragonite will update the `last_refreshed` column before it gets a response back from Xil.

This causes accounts to go into a state that the initer doesn't touch if it has a `last_refreshed` timestamp set but doesn't have a `refresh_token`

```
update account set last_refreshed = NULL where refresh_token = '' and provider = 'ptc'
```

**Comment by jfberry** [comment]
It uses this to mark when it should try again (it doesn't do so for at least an hour). This is expected behaviour.
