### ISSUE TITLE
Make 'populate_invasions' default to 'false' on new areas

### ISSUE THREAD

**Issue by Axiangel** [UnownHash/Dragonite-Public#34]
Newly added areas get Populate Invations = True.
We all know the Invasion scanning is banning accounts so it would be safer to set that to false as default, imo.
Plx.. :-)

**Comment by freakyscientist** [comment]
As far as I know, this only prepares the queue for invasions, and it is not actually scanning the invasions themselves.

**Comment by lenisko** [comment]
If there's no active **Invasion Mode** it won't even populate queues. No harm is done and who knows - maybe in future it will make sense to run those again.
