### ISSUE TITLE
Leveler: Manhattan Route

### ISSUE THREAD

**Issue by lokixx** [UnownHash/Dragonite-Public#8]
CSV for old Lorgnette Nessus Route for Manhattan, NY (if this works for those who can test, I'll add the rest here.
[nessus_newyork_20200627b_uq.csv](https://github.com/UnownHash/Dragonite-Public/files/13341148/nessus_newyork_20200627b_uq.csv)

**Comment by Fabio1988** [comment]
Feel free to open a PR

I added for now a levelroute in this repo

https://github.com/UnownHash/Dragonite-Public/tree/main/dragonite/leveling

**Comment by Fabio1988** [comment]
I will close this for now, thanks for manhattan route, but we should consider to add an up to date route. Therefore I added Zaragoza to the repo.

If anybody can come up with alternatives, feel free to PR :)
